
name: Build project

on:
        push:
                branches: [main]
        pull_request:

jobs:
        build:
                runs-on: windows-latest

                defaults:
                        run:
                                shell: msys2 {0}

                steps:
                        - name: 📥 Checkout repository
                          uses: actions/checkout@v4

                        - name: Get MSYS2
                          uses: msys2/setup-msys2@v2
                          with:
                                msystem: MINGW64
                                update: true
                                install: |
                                  base-devel git
                                  mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-cross-clang mingw-w64-x86_64-gcc
                                  mingw-w64-x86_64-mesa mingw-w64-x86_64-glew mingw-w64-x86_64-glfw
                                  mingw-w64-x86_64-fontconfig mingw-w64-x86_64-freetype mingw-w64-x86_64-libjpeg-turbo mingw-w64-x86_64-libpng mingw-w64-x86_64-libwebp
                                  mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-icu
                                  mingw-w64-x86_64-python

                        - name: Get Qt framework
                          run: |
                            python3 -m ensurepip
                            python3 -m pip install aqtinstall
                            export SETUPTOOLS_USE_DISTUTILS=stdlib
                            python -m aqt install-qt windows desktop 6.9.1 win64_mingw81 -m qtnetworkauth qt5compat

                        - name: Cache build directory
                          uses: actions/cache@v4
                          with:
                                  path: build/
                                  key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp') }}
                                  restore-keys: |
                                          ${{ runner.os }}-build-

                        - name: 🏗️ Configure and build
                          run: |
                                  mkdir -p build
                                  cd build
                                  cmake .. -DCMAKE_PREFIX_PATH=../Qt/6.9.1/gcc_64
                                  cmake --build . -j$(nproc)

                        - name: 📦 Upload executable
                          uses: actions/upload-artifact@v4
                          with:
                                  name: AdvancedEffects
                                  path: |
                                          build/src/app/AdvancedEffects.exe
                                  if-no-files-found: error
